---
  ManilaShares.attach_security_service_to_share_network:
    -
      args:
        security_service_type: "active_directory"
      runner:
        type: "constant"
        times: 10
        concurrency: 10
      context:
        quotas:
          manila:
            share_networks: -1
